name: Auto Update OpenWrt IPK Index

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ipk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ipkg-utils
        run: sudo apt-get update && sudo apt-get install -y ipkg-utils

      - name: Generate Packages index
        run: |
          # Find all directories containing IPK files
          for dir in $(find . -type f -name "*.ipk" -exec dirname {} \; | sort -u); do
            echo "Processing $dir"
            cd "$dir"
            ipkg-make-index . > Packages
            gzip -9c Packages > Packages.gz
            cd - > /dev/null
          done

      - name: Commit and push updated Packages
        uses: EndBug/add-and-commit@v9
        with:
          add: '**/Packages **/Packages.gz'
          message: 'Auto update Packages index for all architectures'
          default_author: github_actions
